services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Form\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model}'

  TYPO3\CMS\Form\Mvc\Configuration\ConfigurationManagerInterface:
    alias: TYPO3\CMS\Form\Mvc\Configuration\ConfigurationManager
    public: true

  TYPO3\CMS\Form\Mvc\Configuration\TypoScriptService:
    public: true

  TYPO3\CMS\Form\Mvc\Persistence\FormPersistenceManagerInterface:
    alias: TYPO3\CMS\Form\Mvc\Persistence\FormPersistenceManager
    public: true

  TYPO3\CMS\Form\Service\TranslationService:
    public: true
    arguments:
      $runtimeCache: '@cache.runtime'

  TYPO3\CMS\Form\Domain\Factory\ArrayFormFactory:
    public: true
    shared: false

  TYPO3\CMS\Form\Domain\Renderer\FluidFormRenderer:
    public: true
    shared: false

  TYPO3\CMS\Form\Domain\Runtime\FormRuntime:
    public: true
    shared: false

  TYPO3\CMS\Form\Mvc\ProcessingRule:
    public: true
    shared: false

  TYPO3\CMS\Form\Mvc\Property\PropertyMappingConfiguration:
    public: true

  TYPO3\CMS\Form\SoftReference\FormPersistenceIdentifierSoftReferenceParser:
    tags:
      - name: softreference.parser
        parserKey: formPersistenceIdentifier

  TYPO3\CMS\Form\Mvc\Property\TypeConverter\FormDefinitionArrayConverter:
    tags:
      - name: extbase.type_converter
        priority: 10
        target: TYPO3\CMS\Form\Type\FormDefinitionArray
        sources: string
